name: "leonardo"
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=leonardo
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_pass
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    secrets:
      - mongo_pass

  frontend:
    build:
      context: leonardo
      target: PROD
    volumes:
      - ./leonardo/:/src
      - www_leonardo:/build

  backend:
    build:
      context: flask
    stop_signal: SIGINT
    environment:
      - MONGO_USER=leonardo
      - MONGO_PASSWORD_FILE=/run/secrets/mongo_pass
      - DEBUG=false
      - FLASK_PORT=1447
    volumes:
      - ./flask/src:/src
    depends_on:
      mongodb:
        condition: service_healthy
    secrets:
      - mongo_pass
  web:
    image: nginx
    environment:
      - DOMANIN=leonardo.racherom.wtf
      - BACKEND_ADDR=backend:1447
    volumes:
      - www_leonardo:/var/www/leonardo
      - ./nginx/app.conf:/tmp/nginx.conf
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:8080
      - 443:8443
    depends_on:
      certbot_init:
        condition: service_completed_successfully
      frontend:
        condition: service_completed_successfully
      backend:
        condition: service_started

  certbot_init:
    image: certbot/certbot
    restart: no
    volumes:
      - ssl_certificates:/etc/letsencrypt
    ports:
      - 80:80
    command: certonly --agree-tos --standalone -n -m admin@racherom.wtf -d leonardo.racherom.wtf

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ssl_certificates:/etc/letsencrypt
      - www_challange:/var/www/certbot
    depends_on:
      - web
    environment:
      - DOMANIN=leonardo.racherom.wtf
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  www_leonardo:

  www_challange:

  mongodb_data:

  ssl_certificates:


networks:
  leonardo:


secrets:
  secret_key:
    file: secrets/secret_key
  mongo_pass:
    file: secrets/mongodb_password
